spring:
  application:
    name: dispatcher-service

  datasource:
    url: jdbc:postgresql://localhost:5433/notix
    username: notix_user
    password: notix_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: dispatcher-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: dispatcher-group
    topics: notifications
  producer:
    email-topic: notifications.email
    sms-topic: notifications.sms
