spring:
  application:
    name: api-service

  datasource:
    url: jdbc:postgresql://localhost:5433/notix
    username: notix_user
    password: notix_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

info:
  app:
    name: api-service
    description: Handles notification submission & publishing
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

kafka:
  producer:
    topic: notifications

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html